### ISSUE TITLE
aws provider locked to 3.10.0

### ISSUE THREAD

**Issue by jakubigla** [clouddrove/terraform-aws-api-gateway#20]
Why this module is locked to aws provider version `3.10.0`?

**Comment by abhilashusha** [comment]
can anyone look into this please?

**Comment by Bobby8249** [comment]
its not locked you can change provider version as per your requirment

**Comment by jakubigla** [comment]
ekhm, It is locked, to `3.10.0` according to what's in the master branch. 
https://github.com/clouddrove/terraform-aws-api-gateway/blob/master/versions.tf#L7
