### ISSUE TITLE
{"message": "Internal server error"}

### ISSUE THREAD

**Issue by ven-rkhadke** [clouddrove/terraform-aws-api-gateway#21]
I copied code and deployed. only change i did is the correct arn of lambda function , also updated region in uri section.
getting Intenal server error for each method.

however , through portal, when i create new resource , add new method and deploy it , then it works.

**Comment by yobooooi** [comment]
Hi, 

Its most likely that you might still need to add a trigger on the lambda function to allow API Gateway to invoke your lambda. This is something I thought the module might do but sitting with the same issue. 

More so, head to Triggers in the Lamda Configuration and add the API Gateway as a trigger and you should be sorted.
