### ISSUE TITLE
"vpc_endpoint_ids" is passed even if  I do not declare it

### ISSUE THREAD

**Issue by basarsoker** [clouddrove/terraform-aws-api-gateway#24]
The default value for the **"vpc_endpoint_ids"** causes the following problem. 

`BadRequestException: VPCEndpoints can only be specified with PRIVATE apis.`

I tried to skip this by giving `[""]` as a value to the variable, however, at that time I encountered the following error 

`Not enough list items. Attribute requires 1 item minimum, but config has only 0 declared`

Finally, as a workaround, I had to comment out [this](https://github.com/clouddrove/terraform-aws-api-gateway/blob/8892b1f0ac2c610283da694d4faa38ed5c957e09/main.tf#L34) line. 

If I am not mistaken, please correct this.

Thanks in advance!

**Comment by anmolnagpal** [comment]
@basarsoker 

Will be great if you can create a pull request for the fix.
