### ISSUE TITLE
Multiple methods under same resource not working [Needing Help]

### ISSUE THREAD

**Issue by sparmarsf** [clouddrove/terraform-aws-api-gateway#27]
Hi, I am trying to test few things with multiple methods under same resource but its not getting provisioned. checking if its limitation of this code or I need to pass the variables differently.
  
-- Current code --

# Api Gateway Resource
    path_parts = ["mytestresource", "mytestresource1"]

  # Api Gateway Method
    method_enabled = true
    http_methods   = ["GET", "GET"]

--- Test ----

mytestresource --> GET, POST, DELETE

**Comment by yadavprakash** [comment]
Hy @sparmarsf if you use multipal method so need to use multipal resource. Thank You
