### ISSUE TITLE
support parent id to resource

### ISSUE THREAD

**Issue by franviera92** [clouddrove/terraform-aws-api-gateway#3]
Please support add parent id in resource

**Comment by anmolnagpal** [comment]
Hello @franviera92 

We are on it, will try to do asap

**Comment by franviera92** [comment]
This

 - /
  - /myresource
   - /myresource/**v1**/

**Comment by abhilashkar** [comment]
@anmolnagpal @nikitadugar Is there a way we can get this enhancement done? . Appreciate your help here
