### ISSUE TITLE
API Gateway Model: Unsupported keyword: dependentRequired

### ISSUE THREAD

**Issue by Perlzx** [clouddrove/terraform-aws-api-gateway#30]
![image](https://user-images.githubusercontent.com/45738403/206929204-6df05c01-72d2-4d05-b438-cb1401342e8f.png)
![image](https://user-images.githubusercontent.com/45738403/206929286-139fea53-689f-4019-b4e9-3616d884393a.png)

This property is exists but i can't apply to my schema

**Comment by mamrajyadav** [comment]
Hi @Perlzx this issue related to your aws keyword this is not supported.
