### ISSUE TITLE
How to set authorizer_ids?

### ISSUE THREAD

**Issue by ARogovsky** [clouddrove/terraform-aws-api-gateway#4]
The module is created a resource module.api-gateway.aws_api_gateway_authorizer.default[0]:
This resource has id value which needs insert into authorizer_ids.
How I can reference to internal module interpolation from module config?

I thinking better use the number of aws_api_gateway_authorizer.default[number].id, where empty is meant, do not use authorizer and another value is the number of method.

**Comment by cdhesse** [comment]
I am seeing the same issue, no way of specifying the authorizor_id since it is internally created by the module.  How do do this?
