### ISSUE TITLE
Request: Invoke URL as an output

### ISSUE THREAD

**Issue by cloud-mt** [clouddrove/terraform-aws-api-gateway#40]
Hi,
Is it possible to have the **invoke URL** of a deployed stage as an output? 
or even the **stage name** would help for a tailored solution to pass the invoke URL as a parameter.

Thanks.

**Comment by mamrajyadav** [comment]
Hi @cloud-mt I have added both outputs but **invoke URL**  did't get in output because it's a sensitive value so now please use latest code for this 
![Screenshot from 2023-06-12 19-59-46](https://github.com/clouddrove/terraform-aws-api-gateway/assets/80300065/ff7c959b-d9cb-411c-83ee-b620412ae43d)

**Comment by cloud-mt** [comment]
Great! thanks @mamrajyadav
