### ISSUE TITLE
more than one method per path_part

### ISSUE THREAD

**Issue by baconsi** [clouddrove/terraform-aws-api-gateway#6]
Is it possible to have more than one http_method per path_part

if  i want path part 
/request
is it possible to have methods
GET
POST

**Comment by git-heera** [comment]
Is it solved? I want to have resource paths like /temp/temp1/temp2 --> Define POST method here

**Comment by mdgrotheer** [comment]
I'd be interested in getting this functionality

**Comment by sify-aws** [comment]
No it is not solved

**Comment by yobooooi** [comment]
> Is it solved? I want to have resource paths like /temp/temp1/temp2 --> Define POST method here

Does the current implementation allow for having an API resource deployed under a nested path ?

/v1/user/update_name -> Define method here
